name: Push

on:
  push:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: axiomhq/setup-axiom@v1
      id: axiom
    - name: Set Axiom Settings
      run: |
        echo "AXIOM_URL=${{ steps.axiom.outputs.url }}" >> $GITHUB_ENV
        echo "AXIOM_TOKEN=${{ steps.axiom.outputs.token }}" >> $GITHUB_ENV
    - name: Setup .Net
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/Axiom.sln
    - name: Test
      run: dotnet test src/Axiom.sln
  docs:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Setup DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
            args: install docfx

      - name: DocFX Build
        working-directory: docs
        run: docfx .\docfx.json
        continue-on-error: false

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/_site
            force_orphan: true